  select
    TICKET_ID,
	AGENT,
	CURRENT_STATUS,
	CHANNEL,
	PRIORITY,
	TO_DATE(SPLIT_PART(DATE_CREATED, ' ', 0), 'MM/DD/YYYY') AS DATE_CREATED,
    TO_DATE(SPLIT_PART(LAST_UPDATED, ' ', 0), 'MM/DD/YYYY') AS LAST_UPDATED,
	hour(to_time(SPLIT_PART(date_created, '022 ', 2))) AS HOUR,
	CATEGORY
    from PC_FIVETRAN_DB.DYNAMODB_WEST.WI_TICKETS
	where DATE_CREATED > '05/15/2022'